name: hackfest_turtley
description: This is our new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  cupertino_icons: ^0.1.3 #allows icon plugin
  flutter_svg: ^0.20.0-nullsafety.3 #allows the us of SVG
  intl: ^0.18.0
  firebase_auth: ^4.2.2
  firebase_core: ^2.9.0
  d_chart: ^2.2.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/ #added for image and icon directory