// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTsj2Rj3zx3ap2-F666q7UpT3yTAroGy0',
    appId: '1:572864098614:web:8b0fa7e12b545f01a58397',
    messagingSenderId: '572864098614',
    projectId: 'hackfest---turtley',
    authDomain: 'hackfest---turtley.firebaseapp.com',
    databaseURL: 'https://hackfest---turtley-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hackfest---turtley.appspot.com',
    measurementId: 'G-XV66PFC7NK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhbP0YAHJhMO2mhH2L24m5OUXJz9WtIjw',
    appId: '1:572864098614:android:9ef51b5955a58883a58397',
    messagingSenderId: '572864098614',
    projectId: 'hackfest---turtley',
    databaseURL: 'https://hackfest---turtley-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hackfest---turtley.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKCsNXSqDIbWQAyP11tKDcVhneQSJWnBc',
    appId: '1:572864098614:ios:845be4f22f5f51e2a58397',
    messagingSenderId: '572864098614',
    projectId: 'hackfest---turtley',
    databaseURL: 'https://hackfest---turtley-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hackfest---turtley.appspot.com',
    iosClientId: '572864098614-gdep4135ghagltvv9ul85rgqdi0gcdlu.apps.googleusercontent.com',
    iosBundleId: 'com.example.hackfestTurtley',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKCsNXSqDIbWQAyP11tKDcVhneQSJWnBc',
    appId: '1:572864098614:ios:845be4f22f5f51e2a58397',
    messagingSenderId: '572864098614',
    projectId: 'hackfest---turtley',
    databaseURL: 'https://hackfest---turtley-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hackfest---turtley.appspot.com',
    iosClientId: '572864098614-gdep4135ghagltvv9ul85rgqdi0gcdlu.apps.googleusercontent.com',
    iosBundleId: 'com.example.hackfestTurtley',
  );
}
